import os
from urllib.parse import quote_plus

BOT_TOKEN = os.getenv("BOT_TOKEN")
CRYPTO_BOT_TOKEN = os.getenv("CRYPTO_BOT_TOKEN")
CRYPTO_API_URL = "https://pay.crypt.bot/api"
ADMIN_ID = 8538723496

_db_url = os.getenv("DATABASE_URL", "")
_db_password = os.getenv("DB_PASSWORD", "")
DATABASE_URL = _db_url.replace("[YOUR-PASSWORD]", quote_plus(_db_password))

# Баннеры
BANNER_FILE_ID = "AgACAgIAAxkBAAMUagkD8srz17wm2JWlcR_0TJOMqNoAAuMYaxv8J0lIIL1mWMHMnpEBAAMCAAN5AAM7BA"
PROFILE_BANNER_FILE_ID = "AgACAgIAAxkBAAMYagkEL1jm_lsQvpEGeRuS49pzz9kAApoTaxsg6DlI720BR6R-tkEBAAMCAAN5AAM7BA"
CARD_BANNER_FILE_ID = "AgACAgIAAxkBAAMWagkEC9WJ85LhsI7UKyhLPMdUCFAAAtwTaxsg6DlItMKzFiDzPzgBAAMCAAN5AAM7BA"
ORDER_BANNER_FILE_ID = "AgACAgIAAxkBAAMWagkEC9WJ85LhsI7UKyhLPMdUCFAAAtwTaxsg6DlItMKzFiDzPzgBAAMCAAN5AAM7BA"
TRANSFER_BANNER_FILE_ID = "AgACAgIAAxkBAAIIe2oNHiBflkbBT9UHU6TSWtYE3wVWAAKpJ2sbVtZoSKUmlbRdOOqzAQADAgADeQADOwQ"
TRANSFER_SELECT_BANNER_FILE_ID = "AgACAgIAAxkBAAIIimoNIJrSgX1xnUAmdEIokg6IBKRDAAK5J2sbVtZoSC5i97-4c4K4AQADAgADeQADOwQ"

# Стикер приветствия
WELCOME_STICKER_ID = "CAACAgIAAxkBAAMpagkLFKC-PjDNsDg3K_AGE_jwrOMAAg4AAw5HxyjWE2CRsGx-mTsE"
